# the rest of the config is taken from config-server
spring:
  application:
    name: subscription # this name will be shown in eureka
  config:
    import: optional:configserver:http://config-server:8888