# the rest of the config is taken from config-server
spring:
  application:
    name: auth # this name will be shown in eureka
  config:
    # if the address of the config-server is not specified, then http://localhost:8888 is used
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}
  profiles:
    # if the profile is not specified, then dev is used
    active: ${SPRING_PROFILES_ACTIVE:dev}