# the name of this file must be exactly like the name of the application
eureka:
  instance:
    prefer-ip-address: false
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8081
  address: localhost

spring:
  cloud:
    inetutils:
      preferred-networks:
        - 127.0.0.1
      ignored-interfaces:
        - docker0
        - veth.*
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:15432/users
    username: username
    password: password

  jpa:
    hibernate:
      ddl-auto: create-drop
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  app:
    jwtSecret: BSyus78W73UHhqpIOJS9Jjd03928u3rdh9UIHD89wh9dw
    jwtExpirationMs: 8640000000