# the name of this file must be exactly like the name of the application
server:
  port: 8080
spring:
  app:
    jwtSecret: BSyus78W73UHhqpIOJS9Jjd03928u3rdh9UIHD89wh9dw
  cloud:
    gateway:
      discovery:
        locator:
          # shows that we have to fetch information about registered microservices from Discovery service
          enabled: true
      routes:
        # if the request path is /api/v1/auth/**, it is redirected to auth microservice
        - id: auth
          uri: lb://auth
          predicates:
            - Path=/api/v1/auth/**

        # if the request path is /internal/auth/**, it is redirected to auth microservice
        - id: auth-internal
          uri: lb://auth
          predicates:
            - Path=/internal/auth/**

        # redirection for swagger requests for auth microservice
        - id: auth-swagger
          uri: lb://auth
          predicates:
            - Path=/auth/v3/api-docs
          filters:
            - RewritePath=/auth/v3/api-docs, /v3/api-docs

        # if the request path is /api/v1/habits/**, it is redirected to habit microservice
        - id: habit
          uri: lb://habit
          predicates:
            - Path=/api/v1/habits/**

        # if the request path is /internal/habits/**, it is redirected to habit microservice
        - id: habit-internal
          uri: lb://habit
          predicates:
            - Path=/internal/habits/**

        # redirection for swagger requests for habit microservice
        - id: habit-swagger
          uri: lb://habit
          predicates:
            - Path=/habit/v3/api-docs
          filters:
            - RewritePath=/habit/v3/api-docs, /v3/api-docs

        # if the request path is /api/v1/reports/**, it is redirected to report microservice
        - id: report
          uri: lb://report
          predicates:
            - Path=/api/v1/reports/**

        # if the request path is /internal/reports/**, it is redirected to report microservice
        - id: report-internal
          uri: lb://report
          predicates:
            - Path=/internal/reports/**

        # redirection for swagger requests for report microservice
        - id: report-swagger
          uri: lb://report
          predicates:
            - Path=/report/v3/api-docs
          filters:
            - RewritePath=/report/v3/api-docs, /v3/api-docs

        # if the request path is /api/v1/subscriptions/**, it is redirected to subscription microservice
        - id: subscription
          uri: lb://subscription
          predicates:
            - Path=/api/v1/subscriptions/**

        # redirection for swagger requests for subscription microservice
        - id: subscription-swagger
          uri: lb://subscription
          predicates:
            - Path=/subscription/v3/api-docs
          filters:
            - RewritePath=/subscription/v3/api-docs, /v3/api-docs

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    urls:
      - name: Auth API
        url: /auth/v3/api-docs
      - name: Habit API
        url: /habit/v3/api-docs
      - name: Report API
        url: /report/v3/api-docs
      - name: Subscription API
        url: /subscription/v3/api-docs
