# the name of this file must be exactly like the name of the application
server:
  port: 8080
spring:
  cloud:
    gateway:
      discovery:
        locator:
          # shows that we have to fetch information about registered microservices from Discovery service
          enabled: true
      routes:
        # if the request path is /api/v1/habits/**, it is redirected to habit microservice
        - id: habit
          uri: lb://habit
          predicates:
            - Path=/api/v1/habits/**
        # if the request path is /api/v1/auth/**, it is redirected to auth microservice
        - id: auth
          uri: lb://auth
          predicates:
            - Path=/api/v1/auth/**