# the name of this file must be exactly like the name of the application
eureka:
  instance:
    prefer-ip-address: false
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

internal:
  token: U8GN1JJG0nSLhyEfon6lllMSqNym45sCnuQhYUgMpQ5esm3F5p5rE

server:
  port: 8083
  address: localhost

spring:
  cloud:
    inetutils:
      preferred-networks:
        - 127.0.0.1
      ignored-interfaces:
        - docker0
        - veth.*
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:15432/reports
    username: username
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: report-group
      auto-offset-reset: latest # only new messages
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer